repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black crud
        always_run: true
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort .
        always_run: true
        language: system
        pass_filenames: false  
      - id: flake8
        name: flake8
        entry: poetry run flake8 crud
        always_run: true
        language: system
        pass_filenames: false     
      - id: mypy
        name: mypy
        entry: poetry run mypy crud
        always_run: true
        language: system
        pass_filenames: false
