name: Linters

on:
  workflow_dispatch
  # pull_request:
  #   types: [opened, reopened]
  #   branches:
  #     - main


jobs:



  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run black
        uses: psf/black@stable 

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run isort
        uses: isort/isort-action@v1

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run flake8
        run: |
          python -m pip install --upgrade flake8
          flake8 crud/

