name: Version Sync

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
  # pull_request:
  #   types: [opened, reopened]
  #   branches:
  #     - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0
      - name: Set version env var
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Git config
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push


      - name: Tag new target
        run: git tag -f $VERSION
      - name: Push new tag
        run: git push  
      
      
      
      # - name: Install poetry
      #   run: pipx install poetry
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     cache: 'poetry'



      # - name: See current Git tag
      #   run: |
      #     git status
      #     git describe --tags


